
#' Basic interactive choropleth
#' 
#' @param x a \code{SpatialPolygonsDataFrame}.
#' @param col.by a column name of x giving values to color polygons.
#' @param breaks  a numeric vector of cut points or a single number of intervals.
#' @param alpha a numeric to control the transparency.
#' @param popup a character vector providing popup content.
#' @param col a vector of color usually generated by color palettes functions.
#' 
#' @export
choropleth <- function(x, col.by, breaks = 5, alpha = 1, col = NULL, popup = NULL, ...){
  
  if(!class(x) == "SpatialPolygonsDataFrame"){
    stop("x must be a SpatialPolygonsDataFrame")
  }
  
  z <- x[[col.by]]
  znum <- as.numeric(z)
  
  if (length(breaks) > 1){
    n <- length(breaks) - 1
  } else {
    n <- breaks
  }
  
  if(is.null(col)){
    gcol <- rev(heat.colors(n))  
  } else {
    gcol <- col
  }
  gcut <- cut(znum, breaks = breaks)
  col <- gcol[as.numeric(gcut)]

  if(is.null(popup)){
    popup <- znum
  }
  
  bbm <- basemap("stamen.toner.lite")
  x.map <- spLayer(x, fill.col = col, fill.alpha = alpha, popup = popup)
  
  win <- apply(bbox(x), 1, mean)

  writeMap(bbm, x.map,  setView = c(win[2], win[1]), ...)

}
